# Generated by Django 4.2.5 on 2024-03-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='creador',
        ),
    ]
