# Generated by Django 4.2.5 on 2024-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0002_remove_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
